// <auto-generated />
using System;
using GuildManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MonProjet.Migrations
{
    [DbContext(typeof(GuildManagerDbContext))]
    [Migration("20260909095636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuildManager.Domain.Entities.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_character_classes");

                    b.ToTable("character_classes", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.CharacterEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildMemberCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_member_character_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot");

                    b.HasKey("Id")
                        .HasName("pk_character_equipments");

                    b.HasIndex("GuildMemberCharacterId")
                        .HasDatabaseName("ix_character_equipments_guild_member_character_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_character_equipments_item_id");

                    b.ToTable("character_equipments", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.CharacterTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseAttack")
                        .HasColumnType("integer")
                        .HasColumnName("base_attack");

                    b.Property<int>("BaseDefence")
                        .HasColumnType("integer")
                        .HasColumnName("base_defence");

                    b.Property<int>("BaseHp")
                        .HasColumnType("integer")
                        .HasColumnName("base_hp");

                    b.Property<int>("BaseMagic")
                        .HasColumnType("integer")
                        .HasColumnName("base_magic");

                    b.Property<int>("BaseRecruitmentCost")
                        .HasColumnType("integer")
                        .HasColumnName("base_recruitment_cost");

                    b.Property<bool>("CanSwitchToHealer")
                        .HasColumnType("boolean")
                        .HasColumnName("can_switch_to_healer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer")
                        .HasColumnName("class_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("RecruitmentInLevel")
                        .HasColumnType("integer")
                        .HasColumnName("recruitment_in_level");

                    b.HasKey("Id")
                        .HasName("pk_character_templates");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("ix_character_templates_class_id");

                    b.ToTable("character_templates", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.Guild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Food")
                        .HasColumnType("integer")
                        .HasColumnName("food");

                    b.Property<int>("FounderUserId")
                        .HasColumnType("integer")
                        .HasColumnName("founder_user_id");

                    b.Property<int>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<bool>("IsDefeated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_defeated");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ReputationTotal")
                        .HasColumnType("integer")
                        .HasColumnName("reputation_total");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.HasIndex("FounderUserId")
                        .HasDatabaseName("ix_guilds_founder_user_id");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.GuildInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_guild_inventories");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_guild_inventories_guild_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_guild_inventories_item_id");

                    b.ToTable("guild_inventories", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.GuildMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsFounder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_founder");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer")
                        .HasColumnName("reputation");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_guild_members");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_guild_members_guild_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_guild_members_user_id");

                    b.ToTable("guild_members", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.GuildMemberCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("character_template_id");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_member_id");

                    b.Property<bool>("IsHealerMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_healer_mode");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<DateTime>("RecruitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recruited_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Xp")
                        .HasColumnType("integer")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_guild_member_characters");

                    b.HasIndex("CharacterTemplateId")
                        .HasDatabaseName("ix_guild_member_characters_character_template_id");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("ix_guild_member_characters_guild_member_id");

                    b.ToTable("guild_member_characters", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BonusAttack")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_attack");

                    b.Property<int>("BonusDefence")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_defence");

                    b.Property<int>("BonusHp")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_hp");

                    b.Property<int>("BonusMagic")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_magic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slot");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseSuccessRate")
                        .HasColumnType("integer")
                        .HasColumnName("base_success_rate");

                    b.Property<int>("MaxPartySize")
                        .HasColumnType("integer")
                        .HasColumnName("max_party_size");

                    b.Property<int>("MinPartySize")
                        .HasColumnType("integer")
                        .HasColumnName("min_party_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("QuestTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_type_id");

                    b.Property<int>("RequiredGuildLevel")
                        .HasColumnType("integer")
                        .HasColumnName("required_guild_level");

                    b.Property<int>("StoryStep")
                        .HasColumnType("integer")
                        .HasColumnName("story_step");

                    b.HasKey("Id")
                        .HasName("pk_quests");

                    b.HasIndex("QuestTypeId")
                        .HasDatabaseName("ix_quests_quest_type_id");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComputedSuccessRate")
                        .HasColumnType("integer")
                        .HasColumnName("computed_success_rate");

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_member_id");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_id");

                    b.Property<DateTime>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.HasKey("Id")
                        .HasName("pk_quest_attempts");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("ix_quest_attempts_guild_member_id");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_quest_attempts_quest_id");

                    b.ToTable("quest_attempts", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestAttemptMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildMemberCharacterId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_member_character_id");

                    b.Property<int>("HpLost")
                        .HasColumnType("integer")
                        .HasColumnName("hp_lost");

                    b.Property<int>("QuestAttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_attempt_id");

                    b.Property<bool>("Survived")
                        .HasColumnType("boolean")
                        .HasColumnName("survived");

                    b.HasKey("Id")
                        .HasName("pk_quest_attempt_members");

                    b.HasIndex("GuildMemberCharacterId")
                        .HasDatabaseName("ix_quest_attempt_members_guild_member_character_id");

                    b.HasIndex("QuestAttemptId")
                        .HasDatabaseName("ix_quest_attempt_members_quest_attempt_id");

                    b.ToTable("quest_attempt_members", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestAttemptRewardLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("QuestAttemptId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_attempt_id");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_type");

                    b.HasKey("Id")
                        .HasName("pk_quest_attempt_reward_logs");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_quest_attempt_reward_logs_item_id");

                    b.HasIndex("QuestAttemptId")
                        .HasDatabaseName("ix_quest_attempt_reward_logs_quest_attempt_id");

                    b.ToTable("quest_attempt_reward_logs", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestMalus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("MalusType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("malus_type");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_id");

                    b.HasKey("Id")
                        .HasName("pk_quest_maluses");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_quest_maluses_quest_id");

                    b.ToTable("quest_maluses", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestReward", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("QuestId")
                        .HasColumnType("integer")
                        .HasColumnName("quest_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int?>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_type");

                    b.HasKey("Id", "QuestId")
                        .HasName("pk_quest_rewards");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_quest_rewards_item_id");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_quest_rewards_quest_id");

                    b.ToTable("quest_rewards", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_quest_types");

                    b.ToTable("quest_types", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.RecruitmentOffer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_member_id");

                    b.Property<int>("CharacterTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("character_template_id");

                    b.Property<int>("GoldCost")
                        .HasColumnType("integer")
                        .HasColumnName("gold_cost");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_purchased");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.HasKey("Id", "GuildMemberId")
                        .HasName("pk_recruitment_offers");

                    b.HasIndex("CharacterTemplateId")
                        .HasDatabaseName("ix_recruitment_offers_character_template_id");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("ix_recruitment_offers_guild_member_id");

                    b.ToTable("recruitment_offers", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildFoodAfter")
                        .HasColumnType("integer")
                        .HasColumnName("guild_food_after");

                    b.Property<int>("GuildGoldAfter")
                        .HasColumnType("integer")
                        .HasColumnName("guild_gold_after");

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_member_id");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.HasKey("Id")
                        .HasName("pk_turns");

                    b.HasIndex("GuildMemberId")
                        .HasDatabaseName("ix_turns_guild_member_id");

                    b.ToTable("turns", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.CharacterEquipment", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.GuildMemberCharacter", null)
                        .WithMany()
                        .HasForeignKey("GuildMemberCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_equipments_guild_member_characters_guild_member_c");

                    b.HasOne("GuildManager.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_equipments_items_item_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.CharacterTemplate", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.CharacterClass", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_character_templates_character_classes_class_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.Guild", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FounderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guilds_users_founder_user_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.GuildInventory", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_inventories_guilds_guild_id");

                    b.HasOne("GuildManager.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guild_inventories_items_item_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.GuildMember", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_members_guilds_guild_id");

                    b.HasOne("GuildManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guild_members_users_user_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.GuildMemberCharacter", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.CharacterTemplate", null)
                        .WithMany()
                        .HasForeignKey("CharacterTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_guild_member_characters_character_templates_character_templ");

                    b.HasOne("GuildManager.Domain.Entities.GuildMember", null)
                        .WithMany()
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_member_characters_guild_members_guild_member_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.Quest", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.QuestType", null)
                        .WithMany()
                        .HasForeignKey("QuestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quests_quest_types_quest_type_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestAttempt", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.GuildMember", null)
                        .WithMany()
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quest_attempts_guild_members_guild_member_id");

                    b.HasOne("GuildManager.Domain.Entities.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quest_attempts_quests_quest_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestAttemptMember", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.GuildMemberCharacter", null)
                        .WithMany()
                        .HasForeignKey("GuildMemberCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quest_attempt_members_guild_member_characters_guild_member_");

                    b.HasOne("GuildManager.Domain.Entities.QuestAttempt", null)
                        .WithMany()
                        .HasForeignKey("QuestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_attempt_members_quest_attempts_quest_attempt_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestAttemptRewardLog", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quest_attempt_reward_logs_items_item_id");

                    b.HasOne("GuildManager.Domain.Entities.QuestAttempt", null)
                        .WithMany()
                        .HasForeignKey("QuestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_attempt_reward_logs_quest_attempts_quest_attempt_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestMalus", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quest_maluses_quests_quest_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.QuestReward", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quest_rewards_items_item_id");

                    b.HasOne("GuildManager.Domain.Entities.Quest", null)
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quest_rewards_quests_quest_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.RecruitmentOffer", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.CharacterTemplate", null)
                        .WithMany()
                        .HasForeignKey("CharacterTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recruitment_offers_character_templates_character_template_id");

                    b.HasOne("GuildManager.Domain.Entities.GuildMember", null)
                        .WithMany()
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recruitment_offers_guild_members_guild_member_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.Turn", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.GuildMember", null)
                        .WithMany()
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_turns_guild_members_guild_member_id");
                });

            modelBuilder.Entity("GuildManager.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("GuildManager.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
